# Generated by Django 5.1 on 2024-09-01 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_article_image_article_video'),
        ('categorias', '0002_alter_categoria_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
    ]
