# Generated by Django 5.1 on 2024-09-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_article_categoria'),
        ('categorias', '0002_alter_categoria_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria'),
        ),
    ]
