# Generated by Django 5.1 on 2024-10-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
