# Generated by Django 5.1 on 2024-10-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_article_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
    ]
