# Generated by Django 5.1 on 2024-11-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_visita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
