# Generated by Django 5.1 on 2024-11-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0013_delete_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
    ]
