# Generated by Django 5.1 on 2024-11-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0014_article_visitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='visitas',
        ),
    ]
