# Generated by Django 5.1 on 2024-09-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMINISTRADOR'), ('editor', 'EDITOR'), ('guest', 'INVITADO')], default='guest', max_length=10),
        ),
    ]
