# Generated by Django 4.0 on 2024-08-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='usuarios',
        ),
    ]
