# Generated by Django 5.1 on 2024-10-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMINISTRADOR'), ('editor', 'EDITOR'), ('autor', 'AUTOR'), ('guest', 'INVITADO')], default='guest', max_length=10),
        ),
    ]
