# Generated by Django 5.1 on 2024-08-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
